const nodemailer = require("nodemailer");

// async..await is not allowed in global scope, must use a wrapper
exports.sendEmail= async(token,email)=> {
console.log("Email");
 const transport = nodemailer.createTransport({
  host: 'smtp.mailtrap.io',
  port: '2525',
  auth: {
    user: 'e9ab597a60e583', //generated by Mailtrap
    pass: '6205603d2529af' //generated by Mailtrap
  }
});

 const mailOptions = {
    from: "Admin <admin@example.com>",
    to: email,
    subject: 'Reset Token',
    text: `Your reset token is: \n ${token} \n\n This token is valid for 15 minutes`, 
    html: `<p> Your reset token is </p><p> ${token}</p> <p>This token is valid for 15 minutes</p>`
};

  // send mail with defined transport object
  await transport.sendMail(mailOptions);
};

